server:
  port: 8099

spring:
  application:
    name: spring-ai-practice

  # Spring Boot 3.4? ??? ?? "spring.http.client.factory=jdk" ??? ???? ???. ??? ??? ????? "reactor"? ???? ImageModel? ?? ?? AI ?????? ???? ????.
  http:
    client:
      factory: jdk

  # AI
  ai:
    chat:
      client:
        enabled: false # ?? ?? ???? - AiConfig ? ??? ChatClient ? ???? ??
    ollama:
      base-url: ${ollama-base-url}
      chat:
        options:
          model: gemma3:27b
          temperature: 0.7
